// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenstarTranslator.Models.Db;

#nullable disable

namespace VenstarTranslator.Migrations
{
    [DbContext(typeof(VenstarTranslatorDataCache))]
    [Migration("20251101203236_AddLastErrorMessage")]
    partial class AddLastErrorMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("VenstarTranslator.Models.Db.TranslatedVenstarSensor", b =>
                {
                    b.Property<byte>("SensorID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreSSLErrors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JSONPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulBroadcast")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SensorID");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("VenstarTranslator.Models.Db.TranslatedVenstarSensor", b =>
                {
                    b.OwnsMany("VenstarTranslator.Models.Db.DataSourceHttpHeader", "Headers", b1 =>
                        {
                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<byte>("TranslatedVenstarSensorSensorID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ID");

                            b1.HasIndex("TranslatedVenstarSensorSensorID");

                            b1.ToTable("DataSourceHttpHeader");

                            b1.WithOwner()
                                .HasForeignKey("TranslatedVenstarSensorSensorID");
                        });

                    b.Navigation("Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
