# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_message.proto
# Protobuf Python Version: 6.33.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '-rc2',
    'sensor_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sensor_message.proto\x12\x07venstar\"\x92\x02\n\rSensorMessage\x12\x30\n\x07\x43ommand\x18\x01 \x02(\x0e\x32\x1f.venstar.SensorMessage.Commands\x12\'\n\nSensorData\x18* \x01(\x0b\x32\x13.venstar.SENSORDATA\"\xa5\x01\n\x08\x43ommands\x12\x11\n\rSETSENSORNAME\x10)\x12\x0e\n\nSENSORDATA\x10*\x12\x0e\n\nSENSORPAIR\x10+\x12\x0e\n\nWIFICONFIG\x10,\x12\x13\n\x0fWIFISCANRESULTS\x10-\x12\x11\n\rFIRMWARECHUNK\x10.\x12\x14\n\x10\x46IRMWARECOMPLETE\x10/\x12\x0b\n\x07SUCCESS\x10~\x12\x0b\n\x07\x46\x41ILURE\x10\x7f\"<\n\nSENSORDATA\x12\x1b\n\x04Info\x18\x01 \x02(\x0b\x32\r.venstar.INFO\x12\x11\n\tSignature\x18\x02 \x02(\t\"\xa0\x03\n\x04INFO\x12\x10\n\x08Sequence\x18\x01 \x02(\r\x12\x10\n\x08SensorId\x18\x02 \x02(\r\x12\x0b\n\x03Mac\x18\x03 \x02(\t\x12\x0f\n\x07\x46wMajor\x18\x04 \x02(\r\x12\x0f\n\x07\x46wMinor\x18\x05 \x02(\r\x12(\n\x05Model\x18\x06 \x02(\x0e\x32\x19.venstar.INFO.SensorModel\x12(\n\x05Power\x18\x07 \x02(\x0e\x32\x19.venstar.INFO.PowerSource\x12\x0c\n\x04Name\x18\x08 \x01(\t\x12&\n\x04Type\x18\t \x01(\x0e\x32\x18.venstar.INFO.SensorType\x12\x13\n\x0bTemperature\x18\n \x01(\r\x12\x0f\n\x07\x42\x61ttery\x18\x0b \x01(\r\x12\x10\n\x08Humidity\x18\x0c \x01(\r\"=\n\nSensorType\x12\x0b\n\x07OUTDOOR\x10\x01\x12\n\n\x06RETURN\x10\x02\x12\n\n\x06REMOTE\x10\x03\x12\n\n\x06SUPPLY\x10\x04\"%\n\x0bPowerSource\x12\x0b\n\x07\x42\x41TTERY\x10\x01\x12\t\n\x05WIRED\x10\x02\"\x1d\n\x0bSensorModel\x12\x0e\n\nTEMPSENSOR\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORMESSAGE']._serialized_start=34
  _globals['_SENSORMESSAGE']._serialized_end=308
  _globals['_SENSORMESSAGE_COMMANDS']._serialized_start=143
  _globals['_SENSORMESSAGE_COMMANDS']._serialized_end=308
  _globals['_SENSORDATA']._serialized_start=310
  _globals['_SENSORDATA']._serialized_end=370
  _globals['_INFO']._serialized_start=373
  _globals['_INFO']._serialized_end=789
  _globals['_INFO_SENSORTYPE']._serialized_start=658
  _globals['_INFO_SENSORTYPE']._serialized_end=719
  _globals['_INFO_POWERSOURCE']._serialized_start=721
  _globals['_INFO_POWERSOURCE']._serialized_end=758
  _globals['_INFO_SENSORMODEL']._serialized_start=760
  _globals['_INFO_SENSORMODEL']._serialized_end=789
# @@protoc_insertion_point(module_scope)
